import { useMemo, useState } from 'react'
import { ArrowDownToLine, ArrowUpFromLine, ChevronRight, Eye, EyeOff, Plus, ShieldCheck, TrendingDown, TrendingUp, Wallet } from 'lucide-react'
import { AssetIcon } from '../components/AssetIcon'
import { Sparkline } from '../components/Sparkline'
import { TradeModal } from '../components/TradeModal'
import { type AssetSymbol, useCryptoStore } from '../store/useCryptoStore'

const money = (value: number, digits = 2) => `$${value.toLocaleString(undefined, { minimumFractionDigits: digits, maximumFractionDigits: digits })}`

function StatCard({ label, value, detail, positive, icon }: { label: string; value: string; detail?: string; positive?: boolean; icon: React.ReactNode }) {
  return <div className="panel flex min-h-[128px] flex-col justify-between p-4 sm:p-5"><div className="flex items-start justify-between"><span className="eyebrow">{label}</span><span className="grid h-8 w-8 place-items-center rounded-lg bg-[#172537] text-muted">{icon}</span></div><div><p className="font-display text-[22px] font-bold tracking-[-.04em] text-white">{value}</p>{detail && <p className={`mt-1 flex items-center gap-1 text-xs font-semibold ${positive ? 'text-lime' : 'text-[#f4788b]'}`}>{positive ? <TrendingUp size={13} /> : <TrendingDown size={13} />}{detail}</p>}</div></div>
}

function PortfolioChart({ values, positive }: { values: number[]; positive: boolean }) {
  return <div className="relative h-[180px] w-full sm:h-[214px]"><div className="pointer-events-none absolute inset-0 flex flex-col justify-between"><span className="border-t border-dashed border-[#203043]" /><span className="border-t border-dashed border-[#203043]" /><span className="border-t border-dashed border-[#203043]" /><span className="border-t border-dashed border-[#203043]" /></div><div className="absolute inset-x-0 bottom-0 top-0 px-1 py-1"><Sparkline values={values} positive={positive} large /></div><div className="absolute -bottom-5 left-0 right-0 flex justify-between text-[10px] font-medium text-[#7d8ca3]"><span>Dec 18</span><span>Dec 25</span><span>Jan 01</span><span>Jan 08</span><span>Jan 15</span></div></div>
}

export function DashboardPage({ isLive, setIsLive }: { isLive: boolean; setIsLive: (value: boolean) => void }) {
  const { assets, cashBalance, transactions, selectedRange, setRange } = useCryptoStore()
  const [hideBalance, setHideBalance] = useState(false)
  const [trade, setTrade] = useState<{ symbol: AssetSymbol; type: 'buy' | 'sell' } | null>(null)
  const totalAssets = assets.reduce((sum, asset) => sum + asset.price * asset.quantity, 0)
  const totalValue = totalAssets + cashBalance
  const dayChange = assets.reduce((sum, asset) => sum + asset.change * asset.quantity, 0)
  const costBasis = assets.reduce((sum, asset) => sum + asset.averagePrice * asset.quantity, 0)
  const totalReturn = totalAssets - costBasis
  const totalReturnPct = (totalReturn / costBasis) * 100
  const chartValues = useMemo(() => Array.from({ length: 64 }, (_, index) => 50 + index * .3 + Math.sin(index / 4) * 4 + Math.sin(index / 10) * 5), [])
  const allocation = assets.filter((asset) => asset.symbol !== 'USDC').map((asset) => ({ ...asset, share: (asset.price * asset.quantity / totalAssets) * 100 }))

  return <>
    <div className="mb-7 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div className="lg:hidden"><h1 className="font-display text-[21px] font-bold tracking-[-.03em] text-white">Good morning, Jordan</h1><p className="mt-1 text-xs text-muted">Here’s what’s happening with your portfolio today.</p></div><div className="hidden lg:block" /><div className="flex items-center gap-2"><span className="flex items-center gap-2 rounded-full border border-[#2a473b] bg-[#10221d] px-3 py-1.5 text-[11px] font-bold text-aqua"><span className={`h-1.5 w-1.5 rounded-full ${isLive ? 'animate-pulse bg-aqua' : 'bg-muted'}`} />{isLive ? 'Live market data' : 'Market data paused'}</span><button onClick={() => setIsLive(!isLive)} className="text-[11px] font-semibold text-muted underline decoration-[#304157] underline-offset-4 hover:text-white">{isLive ? 'Pause' : 'Resume'}</button></div></div>
    <section className="grid gap-5 xl:grid-cols-[minmax(0,1.6fr)_minmax(300px,.8fr)]">
      <div className="panel relative overflow-hidden p-5 sm:p-7"><div className="pointer-events-none absolute -right-14 -top-20 h-56 w-56 rounded-full bg-lime/[.07] blur-3xl" /><div className="relative flex flex-col justify-between gap-6 sm:flex-row"><div><p className="eyebrow">Total portfolio value</p><div className="mt-2 flex items-center gap-3"><p className="font-display text-3xl font-extrabold tracking-[-.06em] text-white sm:text-[38px]">{hideBalance ? '••••••' : money(totalValue)}</p><button aria-label="Toggle balance visibility" onClick={() => setHideBalance(!hideBalance)} className="text-muted transition hover:text-white">{hideBalance ? <EyeOff size={17} /> : <Eye size={17} />}</button></div><p className="mt-2 flex items-center gap-1.5 text-sm font-semibold text-lime"><TrendingUp size={15} />{money(dayChange)} <span className="text-xs font-medium text-[#78905e]">(+{((dayChange / totalAssets) * 100).toFixed(2)}%) today</span></p></div><div className="flex gap-2"><button onClick={() => setTrade({ symbol: 'BTC', type: 'buy' })} className="flex items-center gap-2 rounded-xl bg-lime px-4 py-2.5 text-xs font-bold text-ink transition hover:bg-[#d9ff88]"><Plus size={15} />Buy crypto</button><button onClick={() => setTrade({ symbol: 'BTC', type: 'sell' })} className="hidden items-center gap-2 rounded-xl border border-line bg-[#142030] px-4 py-2.5 text-xs font-bold text-slate-200 transition hover:border-[#33465d] hover:text-white sm:flex"><ArrowUpFromLine size={15} />Sell</button></div></div><div className="mt-11"><PortfolioChart values={chartValues} positive={true} /></div><div className="mt-10 flex items-center justify-between"><div className="flex items-center gap-2 text-[10px] text-muted"><span className="h-2 w-2 rounded-full bg-lime" />Portfolio performance</div><div className="flex items-center gap-1 rounded-lg bg-[#101b2a] p-1">{(['1D', '1W', '1M', '1Y', 'ALL'] as const).map((range) => <button key={range} onClick={() => setRange(range)} className={`rounded-md px-2.5 py-1.5 text-[10px] font-bold transition ${selectedRange === range ? 'bg-[#27384b] text-white' : 'text-muted hover:text-white'}`}>{range}</button>)}</div></div></div>
      <div className="panel flex flex-col p-5 sm:p-6"><div className="flex items-center justify-between"><div><p className="eyebrow">Asset allocation</p><p className="mt-1 text-xs text-muted">Across your holdings</p></div><button aria-label="View allocation details" className="text-muted transition hover:text-white"><ChevronRight size={17} /></button></div><div className="my-6 flex items-center justify-center"><div className="relative grid h-[174px] w-[174px] place-items-center rounded-full" style={{ background: `conic-gradient(#f7931a 0 ${allocation[0]?.share ?? 0}%, #8b93ff ${allocation[0]?.share ?? 0}% ${(allocation[0]?.share ?? 0) + (allocation[1]?.share ?? 0)}%, #a78bfa ${(allocation[0]?.share ?? 0) + (allocation[1]?.share ?? 0)}% ${(allocation[0]?.share ?? 0) + (allocation[1]?.share ?? 0) + (allocation[2]?.share ?? 0)}%, #2775ca ${(allocation[0]?.share ?? 0) + (allocation[1]?.share ?? 0) + (allocation[2]?.share ?? 0)}% 100%)` }}><div className="grid h-[118px] w-[118px] place-items-center rounded-full bg-panel text-center"><div><p className="eyebrow text-[9px]">Invested</p><p className="mt-1 font-display text-xl font-bold text-white">{money(totalAssets, 0)}</p></div></div></div></div><div className="space-y-3">{assets.map((asset) => <div key={asset.symbol} className="flex items-center justify-between text-xs"><div className="flex items-center gap-2"><span className="h-2 w-2 rounded-full" style={{ background: asset.color }} /><span className="font-semibold text-slate-200">{asset.symbol}</span></div><span className="font-semibold text-muted">{((asset.price * asset.quantity / totalAssets) * 100).toFixed(1)}%</span></div>)}</div></div>
    </section>
    <section className="mt-5 grid gap-4 sm:grid-cols-3"><StatCard label="24h change" value={`${dayChange >= 0 ? '+' : ''}${money(dayChange)}`} detail={`+${((dayChange / totalAssets) * 100).toFixed(2)}%`} positive={dayChange >= 0} icon={<TrendingUp size={16} />} /><StatCard label="All-time return" value={`${totalReturn >= 0 ? '+' : ''}${money(totalReturn)}`} detail={`${totalReturnPct >= 0 ? '+' : ''}${totalReturnPct.toFixed(2)}%`} positive={totalReturn >= 0} icon={<BarChartIcon />} /><StatCard label="Cash balance" value={money(cashBalance)} detail="Ready to invest" positive icon={<Wallet size={16} />} /></section>
    <section className="mt-8"><div className="mb-4 flex items-center justify-between"><div><p className="eyebrow">Your portfolio</p><h2 className="mt-1 font-display text-lg font-bold text-white">Holdings</h2></div><button className="flex items-center gap-1 text-xs font-bold text-muted transition hover:text-lime">View all <ChevronRight size={14} /></button></div><div className="panel overflow-hidden"><div className="hidden grid-cols-[2fr_1.2fr_1.1fr_1.1fr_1fr] border-b border-line px-5 py-3 text-[10px] font-bold uppercase tracking-[.16em] text-muted md:grid"><span>Asset</span><span>Price</span><span>Holdings</span><span>Value</span><span className="text-right">24h</span></div>{assets.map((asset) => <div key={asset.symbol} className="grid grid-cols-[1fr_auto] items-center gap-3 border-b border-line px-4 py-4 last:border-0 sm:px-5 md:grid-cols-[2fr_1.2fr_1.1fr_1.1fr_1fr]"><div className="flex items-center gap-3"><AssetIcon asset={asset} size="sm" /><div><p className="text-sm font-bold text-white">{asset.name}</p><p className="text-[11px] text-muted">{asset.symbol}</p></div></div><div className="hidden text-sm font-semibold text-slate-200 md:block">{money(asset.price)}</div><div className="hidden md:block"><p className="text-sm font-semibold text-slate-200">{asset.quantity.toLocaleString(undefined, { maximumFractionDigits: 4 })}</p><p className="text-[11px] text-muted">{asset.symbol}</p></div><div className="text-right md:text-left"><p className="text-sm font-bold text-white">{money(asset.price * asset.quantity)}</p><p className="text-[11px] text-muted md:hidden">{money(asset.price)} · {asset.quantity.toFixed(4)} {asset.symbol}</p></div><div className="hidden items-center justify-end gap-1 text-xs font-bold md:flex" style={{ color: asset.changePct >= 0 ? '#c7f36b' : '#f4788b' }}>{asset.changePct >= 0 ? '+' : ''}{asset.changePct.toFixed(2)}%</div><div className="flex justify-end gap-1.5 md:hidden"><button onClick={() => setTrade({ symbol: asset.symbol, type: 'buy' })} className="rounded-lg bg-lime px-2.5 py-1.5 text-[10px] font-bold text-ink">Buy</button><button onClick={() => setTrade({ symbol: asset.symbol, type: 'sell' })} className="rounded-lg border border-line px-2.5 py-1.5 text-[10px] font-bold text-muted">Sell</button></div></div>)}</div></section>
    <section className="mt-8 grid gap-5 xl:grid-cols-[1.35fr_.65fr]"><div className="panel overflow-hidden"><div className="flex items-center justify-between border-b border-line px-5 py-4"><div><p className="eyebrow">Latest moves</p><h2 className="mt-1 font-display text-base font-bold text-white">Recent activity</h2></div><button className="text-xs font-bold text-muted transition hover:text-lime">See all</button></div>{transactions.slice(0, 3).map((transaction) => { const asset = assets.find((item) => item.symbol === transaction.asset); return <div key={transaction.id} className="flex items-center justify-between gap-3 border-b border-line px-5 py-4 last:border-0"><div className="flex items-center gap-3">{transaction.type === 'deposit' ? <div className="grid h-9 w-9 place-items-center rounded-xl bg-aqua/10 text-aqua"><ArrowDownToLine size={17} /></div> : asset && <AssetIcon asset={asset} size="sm" />}<div><p className="text-sm font-bold capitalize text-white">{transaction.type} {transaction.asset !== 'USD' && transaction.asset}</p><p className="mt-0.5 text-[11px] text-muted">{transaction.date}</p></div></div><div className="text-right"><p className="text-sm font-bold text-white">{transaction.type === 'sell' || transaction.type === 'deposit' ? '+' : '-'}{money(transaction.value)}</p><p className="mt-0.5 text-[11px] font-semibold text-aqua">Completed</p></div></div> })}</div><div className="relative overflow-hidden rounded-2xl border border-[#30483a] bg-[#10231e] p-5 sm:p-6"><div className="pointer-events-none absolute -bottom-8 -right-5 h-36 w-36 rounded-full bg-aqua/[.08] blur-3xl" /><div className="relative"><div className="mb-5 flex h-10 w-10 items-center justify-center rounded-xl bg-aqua/10 text-aqua"><ShieldCheck size={19} /></div><p className="eyebrow text-aqua">Vaultline protection</p><h2 className="mt-2 max-w-[220px] font-display text-lg font-bold leading-7 text-white">Your assets, protected at every step.</h2><p className="mt-2 text-xs leading-5 text-[#91ada4]">We use industry-leading security to keep your account and transactions safe.</p><button className="mt-5 flex items-center gap-1 text-xs font-bold text-aqua transition hover:text-white">Explore security <ChevronRight size={14} /></button></div></div></section>
    {trade && <TradeModal initialSymbol={trade.symbol} initialType={trade.type} onClose={() => setTrade(null)} />}
  </>
}

function BarChartIcon() { return <div className="flex items-end gap-[2px]"><span className="h-2 w-[3px] rounded-full bg-muted" /><span className="h-3.5 w-[3px] rounded-full bg-muted" /><span className="h-5 w-[3px] rounded-full bg-muted" /></div> }
