import { useState } from 'react'
import { ArrowUpRight, ChevronRight, Search, Star, TrendingDown, TrendingUp } from 'lucide-react'
import { AssetIcon } from '../components/AssetIcon'
import { Sparkline } from '../components/Sparkline'
import { TradeModal } from '../components/TradeModal'
import { type AssetSymbol, useCryptoStore } from '../store/useCryptoStore'

const money = (value: number) => `$${value.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`

export function MarketsPage() {
  const { assets } = useCryptoStore()
  const [query, setQuery] = useState('')
  const [trade, setTrade] = useState<{ symbol: AssetSymbol; type: 'buy' | 'sell' } | null>(null)
  const filtered = assets.filter((asset) => `${asset.name} ${asset.symbol}`.toLowerCase().includes(query.toLowerCase()))
  return <>
    <div className="mb-7 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="eyebrow">Market pulse</p><h1 className="mt-2 font-display text-2xl font-bold tracking-[-.04em] text-white">Find your next move</h1><p className="mt-1 text-sm text-muted">Live prices, curated for your portfolio.</p></div><div className="flex items-center gap-2 text-xs text-muted"><span className="h-2 w-2 animate-pulse rounded-full bg-aqua" />Prices update every few seconds</div></div>
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{assets.map((asset) => <div key={asset.symbol} className="panel p-4 transition hover:-translate-y-0.5 hover:border-[#30445e]"><div className="flex items-start justify-between"><div className="flex items-center gap-3"><AssetIcon asset={asset} size="sm" /><div><p className="text-sm font-bold text-white">{asset.symbol}</p><p className="text-[11px] text-muted">{asset.name}</p></div></div><button aria-label={`Add ${asset.symbol} to watchlist`} className="text-muted transition hover:text-lime"><Star size={15} /></button></div><div className="mt-5 flex items-end justify-between"><div><p className="font-display text-lg font-bold tracking-[-.04em] text-white">{money(asset.price)}</p><p className={`mt-1 text-xs font-bold ${asset.changePct >= 0 ? 'text-lime' : 'text-[#f4788b]'}`}>{asset.changePct >= 0 ? '+' : ''}{asset.changePct.toFixed(2)}%</p></div><div className="h-10 w-24"><Sparkline values={asset.sparkline} positive={asset.changePct >= 0} /></div></div></div>)}</section>
    <section className="mt-8"><div className="mb-4 flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><p className="eyebrow">All assets</p><h2 className="mt-1 font-display text-lg font-bold text-white">Explore markets</h2></div><div className="flex items-center gap-2 rounded-xl border border-line bg-panel px-3 py-2.5 sm:w-64"><Search size={15} className="text-muted" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search assets" className="w-full bg-transparent text-xs text-white outline-none placeholder:text-muted" /></div></div><div className="panel overflow-hidden"><div className="hidden grid-cols-[2fr_1.1fr_1.1fr_1.2fr_1fr_auto] border-b border-line px-5 py-3 text-[10px] font-bold uppercase tracking-[.16em] text-muted md:grid"><span>Asset</span><span>Price</span><span>24h change</span><span>Market trend</span><span>In your portfolio</span><span /></div>{filtered.map((asset) => <div key={asset.symbol} className="grid grid-cols-[1fr_auto] items-center gap-3 border-b border-line px-4 py-4 last:border-0 sm:px-5 md:grid-cols-[2fr_1.1fr_1.1fr_1.2fr_1fr_auto]"><div className="flex items-center gap-3"><AssetIcon asset={asset} size="sm" /><div><p className="text-sm font-bold text-white">{asset.name}</p><p className="text-[11px] text-muted">{asset.symbol} · {asset.network}</p></div></div><div className="hidden text-sm font-semibold text-slate-200 md:block">{money(asset.price)}</div><div className={`hidden items-center gap-1 text-xs font-bold md:flex ${asset.changePct >= 0 ? 'text-lime' : 'text-[#f4788b]'}`}>{asset.changePct >= 0 ? <TrendingUp size={13} /> : <TrendingDown size={13} />}{asset.changePct >= 0 ? '+' : ''}{asset.changePct.toFixed(2)}%</div><div className="hidden h-9 w-28 md:block"><Sparkline values={asset.sparkline} positive={asset.changePct >= 0} /></div><div className="hidden text-xs font-semibold text-slate-300 md:block">{asset.quantity.toLocaleString(undefined, { maximumFractionDigits: 4 })} {asset.symbol}</div><button onClick={() => setTrade({ symbol: asset.symbol, type: 'buy' })} className="flex items-center gap-1 rounded-lg bg-lime px-3 py-2 text-[11px] font-bold text-ink transition hover:bg-[#d9ff88]">Buy <ArrowUpRight size={13} /></button><div className="col-span-2 flex items-center justify-between border-t border-line pt-3 md:hidden"><span className={`text-xs font-bold ${asset.changePct >= 0 ? 'text-lime' : 'text-[#f4788b]'}`}>{asset.changePct >= 0 ? '+' : ''}{asset.changePct.toFixed(2)}% today</span><span className="text-xs font-semibold text-slate-300">{money(asset.price)}</span></div></div>)}{filtered.length === 0 && <div className="px-5 py-12 text-center text-sm text-muted">No assets match “{query}”.</div>}</div></section>
    <div className="mt-5 flex items-center justify-between rounded-2xl border border-line bg-[#0d1623] px-5 py-4"><div><p className="text-sm font-bold text-white">Looking for something else?</p><p className="mt-1 text-xs text-muted">Vaultline is adding new assets every week.</p></div><button className="flex items-center gap-1 text-xs font-bold text-lime">View asset roadmap <ChevronRight size={14} /></button></div>
    {trade && <TradeModal initialSymbol={trade.symbol} initialType={trade.type} onClose={() => setTrade(null)} />}
  </>
}
